<script type="text/javascript">
    $$('input[name="meta_title"]').each(function(elm){
        elm.observe('change', function(){
            if(Validation.validate(elm)){
				var store = $('store_switcher') ? $('store_switcher').value : 0;
                updateMetaTitle(elm.readAttribute('data-id'), elm.value, store);
            }
        });
    });

    $$('input[name="meta_description"]').each(function(elm){
        elm.observe('change', function(){
            if(Validation.validate(elm)){
				var store = $('store_switcher') ? $('store_switcher').value : 0;
                updateMetaDescription(elm.readAttribute('data-id'), elm.value, store);
            }
        });
    });

    $$('select[name="meta_robots"]').each(function(elm){
        elm.observe('change', function(){
			var store = $('store_switcher') ? $('store_switcher').value : 0;
            updateMetaRobots(elm.readAttribute('data-id'), elm.value, store);
        });
    });

    $$('input[name="url_key"]').each(function(elm){
        elm.observe('change', function(){
			var store = $('store_switcher') ? $('store_switcher').value : 0;
            updateUrlKey(elm.readAttribute('data-id'), elm.value, store);
        });
    });

    function updateMetaTitle(id, value, store)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/*/updateMetaTitle') ?>', {
            method: 'post',
            parameters: { id: id, title: value, store: store }
        });
    }

    function updateMetaDescription(id, value, store)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/*/updateMetaDescription') ?>', {
            method: 'post',
            parameters: { id: id, description: value, store: store }
        });
    }

    function updateMetaRobots(id, value, store)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/*/updateMetaRobots') ?>', {
            method: 'post',
            parameters: { id: id, robots: value, store: store }
        });
    }

    function updateUrlKey(id, value, store)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/*/updateUrlKey') ?>', {
            method: 'post',
            parameters: { id: id, url: value, store: store }
        });
    }
</script>